import streamlit as st
import pandas as pd
import numpy as np
import pydeck as pdk
import plotly.express as px
import plotly.graph_objects as go
import io
import requests

st.set_page_config(
    page_title="Distribution Management — JC Citi Bike",
    page_icon="🚛",
    layout="wide",
)

DEPOT_LAT          = 40.7326
DEPOT_LNG          = -74.0634
TRUCK_CAP          = 20
MAX_ROUTE_MIN_3PM  = 150
MAX_ROUTE_MIN_10PM = 240

# ── Cost parameters (2025 NY/NJ rates) ────────────────────────────────────────
# Variable cost: fuel $0.33/km (EIA 2025, NY box trucks) + maintenance $0.17/km
#   (ATRI 2025, ~$0.20/mile) + driver $1.20–1.32/km (ZipRecruiter/Indeed 2025,
#   ~$30/hr day / ~$33/hr night at 25 km/h; +$3/hr night differential)
# Fixed cost: 45 min minimum deployment × driver hourly rate (Schuijbroek et al. 2017)
COST_PER_KM_3PM      = 1.70   # day shift  : driver $1.20 + fuel $0.33 + maint $0.17
COST_PER_KM_10PM     = 1.85   # night shift: driver $1.32 + fuel $0.33 + maint $0.20
TRUCK_FIXED_COST_3PM = 23.0   # 45 min × $30/hr (day rate)
TRUCK_FIXED_COST_10PM= 25.0   # 45 min × $33/hr (night rate)

# ── Sidebar: file upload ───────────────────────────────────────────────────────
with st.sidebar:
    st.title("🚛 Distribution Management")
    st.caption("JC / Hoboken Citi Bike Rebalancing")
    st.divider()

    st.subheader("📂 Upload Data Files")
    st.caption("Run `distribution_management.ipynb` first to generate these CSVs.")

    up_routes   = st.file_uploader("distribution_routes.csv",        type="csv")
    up_summary  = st.file_uploader("distribution_summary.csv",       type="csv")
    up_stops    = st.file_uploader("distribution_route_stops.csv",   type="csv")
    up_depots   = st.file_uploader("distribution_depot_deliveries.csv", type="csv")
    up_stations = st.file_uploader("jc_station_master.csv",          type="csv")

# ── Wait for all files ────────────────────────────────────────────────────────
all_uploaded = all([up_routes, up_summary, up_stops, up_depots, up_stations])

if not all_uploaded:
    st.title("🚛 Distribution Management")
    st.info(
        "Upload all 5 CSV files in the sidebar to view the dashboard.  \n\n"
        "**Files needed** (generated by `distribution_management.ipynb`):\n"
        "- `distribution_routes.csv`\n"
        "- `distribution_summary.csv`\n"
        "- `distribution_route_stops.csv`\n"
        "- `distribution_depot_deliveries.csv`\n"
        "- `jc_station_master.csv`  *(generated by `dsops-optimization.ipynb`)*"
    )
    uploaded = sum([bool(up_routes), bool(up_summary), bool(up_stops),
                    bool(up_depots), bool(up_stations)])
    st.progress(uploaded / 5, text=f"{uploaded} / 5 files uploaded")
    st.stop()

# ── Load uploaded files ────────────────────────────────────────────────────────
@st.cache_data
def load_data(r, s, st_, d, sta):
    routes   = pd.read_csv(io.BytesIO(r))
    summary  = pd.read_csv(io.BytesIO(s))
    stops    = pd.read_csv(io.BytesIO(st_))
    depots   = pd.read_csv(io.BytesIO(d))
    stations = pd.read_csv(io.BytesIO(sta), dtype={"station_id": str})
    for df in [routes, summary, stops, depots]:
        df["date"] = pd.to_datetime(df["date"])
    return routes, summary, stops, depots, stations

routes, summary, stops, depots, stations = load_data(
    up_routes.read(), up_summary.read(), up_stops.read(),
    up_depots.read(), up_stations.read()
)

coord_map = {r["station_id"]: (r["lat"], r["lng"]) for _, r in stations.iterrows()}
coord_map["__DEPOT__"] = (DEPOT_LAT, DEPOT_LNG)

# ── Window selector (in sidebar, after upload) ────────────────────────────────
with st.sidebar:
    st.divider()
    dates = sorted(summary["date"].dt.date.unique())
    sel_date = st.selectbox("Select date", dates, index=0)

    sel_rt_label = st.radio(
        "Review window",
        ["🌆  3:00 PM  (evening prep)", "🌙  10:00 PM  (overnight prep)"],
    )
    rt_code  = "15:00" if "3:00 PM" in sel_rt_label else "22:00"
    rt_label = "3:00 PM" if rt_code == "15:00" else "10:00 PM"

    st.divider()
    st.subheader("May 2026 totals")
    st.metric("Total truck-routes",      f"{int(summary['n_trucks'].sum()):,}")
    st.metric("Total bikes transported", f"{int(summary['total_bikes'].sum()):,}")
    st.metric("Total distance",          f"{summary['total_distance_km'].sum():,.0f} km")
    st.metric("Total routing cost",      f"${summary['total_cost'].sum():,.2f}")

# ── Filter to selected window ─────────────────────────────────────────────────
win_routes  = routes[(routes["date"].dt.date  == sel_date) & (routes["review_time"] == rt_code)].copy()
win_summary = summary[(summary["date"].dt.date == sel_date) & (summary["review_time"] == rt_code)]
win_stops   = stops[(stops["date"].dt.date     == sel_date) & (stops["review_time"]   == rt_code)].copy()
win_depots  = depots[(depots["date"].dt.date   == sel_date) & (depots["review_time"]  == rt_code)]

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🚛 Distribution Management")
st.markdown(
    f"**{sel_date}  ·  {rt_label} window**  ·  "
    "CW + 2-opt + Or-opt + PDP  ·  Jersey City / Hoboken Citi Bike"
)

# ── KPI cards ─────────────────────────────────────────────────────────────────
if not win_summary.empty:
    row = win_summary.iloc[0]
    c1,c2,c3,c4,c5,c6 = st.columns(6)
    c1.metric("Trucks",         int(row["n_trucks"]))
    c2.metric("Tasks",          int(row["n_tasks"]))
    c3.metric("Bikes moved",    int(row["total_bikes"]))
    c4.metric("Distance",       f"{row['total_distance_km']:.1f} km")
    c5.metric("Total cost",     f"${row['total_cost']:.2f}")
    c6.metric("Max route time", f"{row['max_route_time_min']:.0f} min")
    # Cost breakdown (variable + fixed) if columns are present
    has_cost_split = "variable_cost" in row and "fixed_cost" in row
    if has_cost_split:
        st.caption(
            f"Variable cost (distance): **${row['variable_cost']:.2f}**  ·  "
            f"Fixed cost ({int(row['n_trucks'])} trucks × ${'23' if rt_code=='15:00' else '25'}): **${row['fixed_cost']:.2f}**  ·  "
            f"S→S tasks: **{int(row['n_ss_tasks'])}**  ·  "
            f"D→S deliveries: **{int(row['n_depot_tasks'])}**  ·  "
            f"S→D pickups: **{int(row['n_std_tasks']) if 'n_std_tasks' in row and not pd.isna(row.get('n_std_tasks',0)) else 0}**  ·  "
            f"Capacity: peak load ≤ {TRUCK_CAP} bikes  ·  Time limit: {MAX_ROUTE_MIN_3PM} min (3PM) / {MAX_ROUTE_MIN_10PM} min (10PM)"
        )
    else:
        st.caption(
            f"S→S tasks: **{int(row['n_ss_tasks'])}**  ·  "
            f"D→S deliveries: **{int(row['n_depot_tasks'])}**  ·  "
            f"S→D pickups: **{int(row['n_std_tasks']) if 'n_std_tasks' in row and not pd.isna(row.get('n_std_tasks',0)) else 0}**  ·  "
            f"Capacity: peak load ≤ {TRUCK_CAP} bikes  ·  Time limit: {MAX_ROUTE_MIN_3PM} min (3PM) / {MAX_ROUTE_MIN_10PM} min (10PM)"
        )
else:
    st.info("No distribution data for this window.")
    st.stop()

st.divider()

# ── Map ───────────────────────────────────────────────────────────────────────
st.subheader("🗺️ Truck Routes")

TRUCK_COLORS = [
    [31,119,180],[255,127,14],[44,160,44],[214,39,40],[148,103,189],
    [140,86,75],[227,119,194],[23,190,207],[188,189,34],[127,127,127],
    [174,199,232],[255,187,120],[152,223,138],[255,152,150],[197,176,213],
    [196,156,148],[247,182,210],[199,199,199],[219,219,141],[158,218,229],
]

@st.cache_data(show_spinner=False)
def get_osrm_path(waypoints: tuple) -> list:
    """Fetch actual road geometry from OSRM for a sequence of [lng, lat] waypoints.
    Falls back to straight-line coords if the API is unreachable."""
    coords_str = ";".join(f"{lng},{lat}" for lng, lat in waypoints)
    url = (
        f"http://router.project-osrm.org/route/v1/driving/{coords_str}"
        "?overview=full&geometries=geojson"
    )
    try:
        resp = requests.get(url, timeout=6)
        if resp.status_code == 200:
            data = resp.json()
            if data.get("code") == "Ok":
                return data["routes"][0]["geometry"]["coordinates"]
    except Exception:
        pass
    return list(waypoints)  # fallback: straight line between waypoints

path_rows, visited_ids = [], set()
for _, r in win_routes.iterrows():
    raw_stops = [s.strip() for s in r["route"].split("→")]
    waypoints = []
    for sid in raw_stops:
        if sid in coord_map:
            waypoints.append((coord_map[sid][1], coord_map[sid][0]))  # lng, lat
            if sid != "__DEPOT__":
                visited_ids.add(sid)
    if len(waypoints) >= 2:
        road_path = get_osrm_path(tuple(waypoints))
        c = TRUCK_COLORS[(int(r["truck_id"]) - 1) % len(TRUCK_COLORS)]
        path_rows.append({
            "path":        road_path,
            "color":       c,
            "truck_id":    int(r["truck_id"]),
            "n_tasks":     int(r["n_tasks"]),
            "bikes":       int(r["bikes_transported"]),
            "peak_load":   int(r["peak_load"]) if "peak_load" in r else 0,
            "distance_km": float(r["distance_km"]),
            "time_min":    float(r["time_min"]),
        })

visited_df  = stations[stations["station_id"].isin(visited_ids)].copy()
inactive_df = stations[~stations["station_id"].isin(visited_ids)].copy()

layers = [
    pdk.Layer("ScatterplotLayer", data=inactive_df,
              get_position=["lng","lat"], get_radius=35,
              get_fill_color=[100,100,120,140]),
    pdk.Layer("ScatterplotLayer", data=visited_df,
              get_position=["lng","lat"], get_radius=55,
              get_fill_color=[59,130,246,230], pickable=True),
    pdk.Layer("PathLayer", data=path_rows,
              get_path="path", get_color="color", get_width=5,
              width_min_pixels=2, pickable=True),
    pdk.Layer("ScatterplotLayer",
              data=[{"lat": DEPOT_LAT, "lng": DEPOT_LNG}],
              get_position=["lng","lat"], get_radius=120,
              get_fill_color=[220,38,38,230]),
]
view = pdk.ViewState(latitude=40.722, longitude=-74.048, zoom=12.5, pitch=0)
st.pydeck_chart(pdk.Deck(
    layers=layers, initial_view_state=view,
    tooltip={"html": (
        "<b>Truck {truck_id}</b><br/>"
        "Tasks: {n_tasks}<br/>"
        "Total bikes transported: {bikes}<br/>"
        "Peak load (max at once): {peak_load} bikes<br/>"
        "Distance: {distance_km} km  ·  Time: {time_min} min"
    )},
    map_style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",
), height=460, use_container_width=True)
st.caption(
    "🔴 Depot (Journal Square)  ·  🔵 Active stations  ·  "
    "Grey = inactive  ·  Lines = actual OSRM road paths (colour = one truck)"
)

st.divider()

# ── Route summary table ───────────────────────────────────────────────────────
st.subheader(f"📋 Route Summary — {len(win_routes)} trucks dispatched")

if not win_routes.empty:
    col_order = ["truck_id","n_tasks","bikes_transported","peak_load",
                 "distance_km","variable_cost","fixed_cost","cost","time_min","has_depot_task"]
    col_order = [c for c in col_order if c in win_routes.columns]
    rename_map = {
        "truck_id":          "Truck #",
        "n_tasks":           "Tasks",
        "bikes_transported": "Total bikes",
        "peak_load":         "Peak load",
        "distance_km":       "Dist (km)",
        "variable_cost":     "Var cost ($)",
        "fixed_cost":        "Fixed ($)",
        "cost":              "Total cost ($)",
        "time_min":          "Time (min)",
        "has_depot_task":    "Depot task?",
    }
    st.dataframe(
        win_routes[col_order].rename(columns=rename_map),
        use_container_width=True, hide_index=True
    )
    st.caption(
        f"**Var cost** = ${'1.70' if rt_code=='15:00' else '1.85'}/km × road distance (OSRM).  "
        f"**Fixed cost** = ${'23' if rt_code=='15:00' else '25'}/truck dispatch.  "
        "**Peak load** = max bikes on truck at any moment (cap = 20).  "
        "Stops may be interleaved — e.g. pickup A → pickup B → dropoff A → dropoff B."
    )
    # Stacked bar: variable vs fixed cost per truck
    if "variable_cost" in win_routes.columns:
        fig_cost = go.Figure()
        fig_cost.add_trace(go.Bar(
            name="Variable (distance)", x=win_routes["truck_id"],
            y=win_routes["variable_cost"], marker_color="#3b82f6"
        ))
        fig_cost.add_trace(go.Bar(
            name=f"Fixed (dispatch ${23 if rt_code == '15:00' else 25}/truck)", x=win_routes["truck_id"],
            y=win_routes["fixed_cost"], marker_color="#f97316"
        ))
        fig_cost.update_layout(
            barmode="stack", height=260,
            title="Cost breakdown per truck — variable (distance) vs fixed (dispatch)",
            xaxis_title="Truck #", yaxis_title="Cost ($)",
            legend=dict(orientation="h", y=1.15),
            margin=dict(t=50, b=0, l=0, r=0)
        )
        st.plotly_chart(fig_cost, use_container_width=True)

st.divider()

# ── Truck drill-down: stop-by-stop ────────────────────────────────────────────
st.subheader("🔍 Truck Stop-by-Stop Detail")

if not win_stops.empty:
    truck_ids = sorted(win_routes["truck_id"].unique())
    sel_truck = st.selectbox(
        "Select a truck to inspect",
        truck_ids,
        format_func=lambda t: (
            f"Truck {t}  —  "
            f"{int(win_routes[win_routes['truck_id']==t]['n_tasks'].iloc[0])} tasks  ·  "
            f"{int(win_routes[win_routes['truck_id']==t]['bikes_transported'].iloc[0])} bikes  ·  "
            f"{win_routes[win_routes['truck_id']==t]['time_min'].iloc[0]:.0f} min"
        )
    )

    truck_stops = win_stops[win_stops["truck_id"] == sel_truck].copy()

    # Collapse consecutive same-action, same-station rows into one summary row
    _rows, _i, _arr = [], 0, truck_stops.to_dict('records')
    while _i < len(_arr):
        _r = _arr[_i]
        if _r["action"] in ("PICKUP", "DROPOFF"):
            _grp = [_r]
            _j = _i + 1
            while (_j < len(_arr)
                   and _arr[_j]["action"] == _r["action"]
                   and _arr[_j].get("station_id") == _r.get("station_id")):
                _grp.append(_arr[_j]); _j += 1
            _m = dict(_grp[0])
            _m["bikes_change"] = sum(g["bikes_change"] for g in _grp)
            _m["load_after"]   = _grp[-1]["load_after"]
            _m["_depot_count"] = len(_grp) if (_r["action"] == "PICKUP" and "Depot" in str(_r.get("station_name", ""))) else 0
            _rows.append(_m); _i = _j
        else:
            _r["_depot_count"] = 0; _rows.append(_r); _i += 1
    truck_stops = pd.DataFrame(_rows).reset_index(drop=True)

    col_l, col_r = st.columns([1.2, 1])

    with col_l:
        ACTION_EMOJI = {"START": "🏭", "PICKUP": "📦", "DROPOFF": "✅", "RETURN": "🏠"}
        truck_stops["#"]          = range(len(truck_stops))
        truck_stops["Action"]     = truck_stops["action"].map(ACTION_EMOJI).fillna("") + " " + truck_stops["action"]
        truck_stops["Station"]    = truck_stops["station_name"]
        truck_stops["Bikes Δ"]    = truck_stops["bikes_change"].apply(
            lambda x: f"+{x}" if x > 0 else (str(x) if x < 0 else "—")
        )
        truck_stops["Load after"] = truck_stops["load_after"].apply(
            lambda x: f"{x} / {TRUCK_CAP}" if x > 0 else "0"
        )
        truck_stops["Type"] = truck_stops.apply(
            lambda r: (
                f"Depot→S ({int(r['_depot_count'])} deliveries)" if r.get("_depot_count", 0) > 1
                else ("Depot→S" if r["task_type"] == "depot_delivery"
                      else ("S→D" if r["task_type"] == "station_to_depot"
                            else ("S→S" if r["task_type"] == "station_to_station" else "")))
            ), axis=1
        )
        st.dataframe(
            truck_stops[["#","Action","Station","Bikes Δ","Load after","Type"]],
            use_container_width=True, hide_index=True, height=420
        )

    with col_r:
        plot_stops = truck_stops[truck_stops["action"].isin(["PICKUP","DROPOFF"])].copy()
        plot_stops["label"] = (
            plot_stops["stop_num"].astype(str) + ". "
            + plot_stops["action"] + " @ "
            + plot_stops["station_id"]
        )
        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=plot_stops["label"],
            y=plot_stops["load_after"],
            marker_color=["#3b82f6" if a == "PICKUP" else "#f97316"
                          for a in plot_stops["action"]],
            text=plot_stops["load_after"],
            textposition="outside",
        ))
        fig.add_hline(y=TRUCK_CAP, line_dash="dash", line_color="red",
                      annotation_text=f"Capacity limit ({TRUCK_CAP})",
                      annotation_position="top right")
        fig.update_layout(
            title=f"Truck {sel_truck} — bikes on board after each stop",
            yaxis_title="Bikes on truck", yaxis_range=[0, TRUCK_CAP + 3],
            height=380, margin=dict(t=50,b=0,l=0,r=0), showlegend=False,
        )
        fig.update_xaxes(tickangle=45, tickfont_size=8)
        st.plotly_chart(fig, use_container_width=True)

        r_row = win_routes[win_routes["truck_id"] == sel_truck].iloc[0]
        tot_bikes = truck_stops[truck_stops["action"] == "PICKUP"]["bikes_change"].sum()
        has_split = "variable_cost" in r_row and "fixed_cost" in r_row
        cost_rows = (
            f"| Variable cost (distance) | ${r_row['variable_cost']:.2f} |\n"
            f"| Fixed cost (dispatch) | ${r_row['fixed_cost']:.2f} |\n"
            f"| **Total cost** | **${r_row['cost']:.2f}** |"
            if has_split else
            f"| Cost | ${r_row['cost']:.2f} |"
        )
        st.markdown(f"""
| | |
|---|---|
| Pickup stops | {(truck_stops['action']=='PICKUP').sum()} |
| Dropoff stops | {(truck_stops['action']=='DROPOFF').sum()} |
| Total bikes handled | **{int(tot_bikes)}** |
| Peak load (max at once) | **{int(r_row.get('peak_load', 0))} / {TRUCK_CAP}** |
| Distance | {r_row['distance_km']:.2f} km |
| Route time | {r_row['time_min']:.0f} min |
{cost_rows}
        """)

st.divider()

# ── Why so many trucks? ───────────────────────────────────────────────────────
with st.expander("📊 Why this many trucks? — Time-limit analysis", expanded=False):
    st.markdown(
        "Trucks can carry bikes from multiple tasks at once — pickups and dropoffs are **interleaved** for efficiency.  \n"
        f"The **time limit ({MAX_ROUTE_MIN_3PM} min for 3PM · {MAX_ROUTE_MIN_10PM} min for 10PM)** is the binding merge constraint.  \n"
        "Windows with long-distance tasks hit the cap earlier and need more trucks."
    )
    if not win_routes.empty:
        fig_t = px.bar(
            win_routes.sort_values("truck_id"),
            x="truck_id", y="time_min",
            color="n_tasks", color_continuous_scale="Blues",
            text="n_tasks",
            labels={"truck_id":"Truck #","time_min":"Route time (min)","n_tasks":"Tasks"},
            title=f"Route duration per truck — {sel_date} {rt_label}",
        )
        rt_limit = MAX_ROUTE_MIN_3PM if rt_code == "15:00" else MAX_ROUTE_MIN_10PM
        fig_t.add_hline(y=rt_limit, line_dash="dash", line_color="red",
                        annotation_text=f"{rt_limit} min limit")
        fig_t.update_layout(height=320, margin=dict(t=40,b=0,l=0,r=0))
        st.plotly_chart(fig_t, use_container_width=True)
        st.caption(f"Bar height = route time. Number = tasks on that truck. Red line = {rt_limit} min cap ({rt_label}).")

st.divider()

# ── Depot deliveries ──────────────────────────────────────────────────────────
if not win_depots.empty:
    with st.expander(f"🏭 Depot Deliveries — {len(win_depots)} stations need direct refill"):
        st.info(
            "These stations had unmet demand after optimisation (in-system surplus was insufficient). "
            "Bikes are dispatched directly from the depot."
        )
        depot_col = next((c for c in ["depot_bikes_delivered","depot_bikes_needed"] if c in win_depots.columns), None)
        want_cols = ["station_id","Required_Qi","received", depot_col]
        depot_cols = [c for c in want_cols if c and c in win_depots.columns]
        rename_map = {
            "station_id":           "Station",
            "Required_Qi":          "Bikes needed",
            "received":             "Received (system)",
            "depot_bikes_delivered":"From depot",
            "depot_bikes_needed":   "From depot",
        }
        sort_col = rename_map.get(depot_col, "From depot") if depot_col else None
        df_dep = win_depots[depot_cols].rename(columns=rename_map)
        if sort_col and sort_col in df_dep.columns:
            df_dep = df_dep.sort_values(sort_col, ascending=False)
        st.dataframe(df_dep, use_container_width=True, hide_index=True)

st.divider()

# ── Monthly charts ────────────────────────────────────────────────────────────
st.subheader("📈 Monthly Overview — May 2026")

c1,c2 = st.columns(2)
with c1:
    fig1 = px.bar(summary, x="date", y="n_trucks", color="review_time", barmode="group",
                  color_discrete_map={"15:00":"#f97316","22:00":"#7c3aed"},
                  labels={"n_trucks":"Trucks","date":"Date","review_time":"Window"},
                  title="Trucks dispatched per day")
    fig1.update_layout(height=300, margin=dict(t=40,b=0,l=0,r=0))
    fig1.for_each_trace(lambda t: t.update(name="3:00 PM" if t.name=="15:00" else "10:00 PM"))
    st.plotly_chart(fig1, use_container_width=True)

with c2:
    if "variable_cost" in summary.columns and "fixed_cost" in summary.columns:
        fig2 = go.Figure()
        for rt_val, rt_name, color in [("15:00","3:00 PM","#f97316"),("22:00","10:00 PM","#7c3aed")]:
            sub = summary[summary["review_time"] == rt_val]
            fig2.add_trace(go.Bar(name=f"Var {rt_name}", x=sub["date"],
                                  y=sub["variable_cost"], marker_color=color, opacity=0.9))
            fig2.add_trace(go.Bar(name=f"Fixed {rt_name}", x=sub["date"],
                                  y=sub["fixed_cost"], marker_color=color, opacity=0.45))
        fig2.update_layout(barmode="stack", height=300, margin=dict(t=40,b=0,l=0,r=0),
                           title="Distribution cost per day (variable + fixed)",
                           yaxis_title="Cost ($)", legend=dict(font_size=9))
    else:
        fig2 = px.bar(summary, x="date", y="total_cost", color="review_time", barmode="group",
                      color_discrete_map={"15:00":"#f97316","22:00":"#7c3aed"},
                      labels={"total_cost":"Cost ($)","date":"Date","review_time":"Window"},
                      title="Distribution cost per day ($)")
        fig2.update_layout(height=300, margin=dict(t=40,b=0,l=0,r=0))
        fig2.for_each_trace(lambda t: t.update(name="3:00 PM" if t.name=="15:00" else "10:00 PM"))
    st.plotly_chart(fig2, use_container_width=True)

c3,c4 = st.columns(2)
with c3:
    fig3 = px.bar(summary, x="date", y="total_bikes", color="review_time", barmode="group",
                  color_discrete_map={"15:00":"#f97316","22:00":"#7c3aed"},
                  labels={"total_bikes":"Bikes","date":"Date","review_time":"Window"},
                  title="Bikes transported per day")
    fig3.update_layout(height=300, margin=dict(t=40,b=0,l=0,r=0))
    fig3.for_each_trace(lambda t: t.update(name="3:00 PM" if t.name=="15:00" else "10:00 PM"))
    st.plotly_chart(fig3, use_container_width=True)

with c4:
    fig4 = px.histogram(routes, x="time_min", nbins=30,
                        color_discrete_sequence=["#3b82f6"],
                        labels={"time_min":"Route duration (min)"},
                        title="Route duration distribution (all windows)")
    fig4.add_vline(x=MAX_ROUTE_MIN_3PM, line_dash="dash", line_color="orange",
                   annotation_text=f"{MAX_ROUTE_MIN_3PM} min (3PM)", annotation_position="top left")
    fig4.add_vline(x=MAX_ROUTE_MIN_10PM, line_dash="dash", line_color="red",
                   annotation_text=f"{MAX_ROUTE_MIN_10PM} min (10PM)", annotation_position="top right")
    fig4.update_layout(height=300, margin=dict(t=40,b=0,l=0,r=0))
    st.plotly_chart(fig4, use_container_width=True)

st.divider()

# ── Task breakdown ────────────────────────────────────────────────────────────
st.subheader("📦 Task Breakdown")
c5,c6 = st.columns(2)
with c5:
    pie_df = pd.DataFrame({
        "Type":  ["Station-to-Station (S→S)","Depot-to-Station (D→S)","Station-to-Depot (S→D)"],
        "Tasks": [int(summary["n_ss_tasks"].sum()), int(summary["n_depot_tasks"].sum()),
                  int(summary["n_std_tasks"].sum()) if "n_std_tasks" in summary.columns else 0],
    })
    fig5 = px.pie(pie_df, names="Type", values="Tasks",
                  color_discrete_sequence=["#3b82f6","#f97316","#16a34a"],
                  title="Task type breakdown — May 2026")
    fig5.update_layout(height=280, margin=dict(t=40,b=0,l=0,r=0))
    st.plotly_chart(fig5, use_container_width=True)

with c6:
    if "peak_load" in routes.columns:
        fig6 = px.histogram(routes, x="peak_load", nbins=20,
                            color_discrete_sequence=["#7c3aed"],
                            labels={"peak_load":"Peak load (bikes)"},
                            title="Peak load per route (max bikes on truck at once)")
        fig6.add_vline(x=TRUCK_CAP, line_dash="dash", line_color="red",
                       annotation_text=f"Cap ({TRUCK_CAP})", annotation_position="top right")
        fig6.update_layout(height=280, margin=dict(t=40,b=0,l=0,r=0))
        st.plotly_chart(fig6, use_container_width=True)

st.divider()

with st.expander("📚 Model assumptions & references"):
    st.markdown("""
| Parameter | Value | Evidence |
|-----------|-------|----------|
| Truck capacity | **20 bikes** | Schuijbroek et al. (2017); Citi Bike Truck Trike specs |
| Capacity check | **running load ≤ 20 at every stop** | Flexible PDP: pickups and deliveries interleaved; load tracked stop-by-stop |
| Load/unload time | **1 min / bike / side** | Schuijbroek et al. (2017, §3.2) |
| Truck speed | **25 km/h** | NYC DOT — JC/Hoboken off-peak |
| Cost per km | **$1.70 (3PM) · $1.85 (10PM)** | Fuel $0.33/km (EIA 2025, NY box trucks) + maintenance $0.17–0.20/km (ATRI 2025) + driver $1.20/km day · $1.32/km night ($30–33/hr at 25 km/h; ZipRecruiter/Indeed 2025 NY/NJ) |
| Fixed dispatch cost | **$23/truck (3PM) · $25/truck (10PM)** | 45 min minimum deployment × driver rate ($30/hr day · $33/hr night incl. +$3/hr night differential); structure from Schuijbroek et al. (2017) |
| Max route time | **150 min (3PM) · 240 min (10PM)** | 3PM: shorter shift before evening peak; 10PM: 4 h cap with 3 h buffer |
| Depot | **Journal Square, JC** | Central hub; truck-accessible |
| Algorithm Phase 1 | **Clarke-Wright Savings** | Clarke & Wright (1964) OR 12(4):568–581 |
| Algorithm Phase 2 | **2-opt intra-route (task)** | Lin (1965) Bell Sys. Tech. J. 44(10):2245–2269 |
| Algorithm Phase 3 | **Or-opt inter-route (task)** | Potvin & Rousseau (1995) INFORMS J. Comp. 7(4) |
| Algorithm Phase 4 | **stop_2opt — flexible PDP** | Precedence + capacity feasibility on stop sequence |

**References:**
Clarke & Wright (1964) · Lin (1965) · Potvin & Rousseau (1995) · Schuijbroek et al. (2017) EJOR 257(3) · Lowalekar et al. (2017) ICAPS
    """)
